#!/bin/zsh
clear
exe=dan_basic
current_dir=$(pwd)
# directories=('lexer' 'parser' 'test' '.')
directories=('.')
dir=${0:a:h}
arg=$1

# Generate function headers for all *.c files
for directory in $directories; do
    for file in $directory/*.c; do
        # echo "... generating function headers for $file ..."
        file_name=${file:0:-2}
        if [[ $file_name != "./main" ]]; then
            zsh ~$dir/generate_function_declaration.sh $file_name 
            mv $file_name.c.generated.h autogenerated/${file_name##*/}.c.generated.h
        fi
    done
done

# echo "... compiling ..."
source ~/$dir/compile.sh

if [[ $? -eq 0 ]]; then
    # echo "... beginning execution of $exe ..."
    if [[ -z $arg ]]; then
        ./$exe
    else
        ./$exe $arg
    fi
fi