struct ParseStmts *new_parse_stmts(struct Lexer *lexer);
struct ParseStmts *parse_stmts(struct Lexer *lexer);
struct ParseStmts *parse_assignment(char *var_name, struct ParseStmts *parser);
struct ParseStmts *parse_declarations(struct ParseStmts *parser);
struct ParseStmts *parse_if(struct ParseStmts *parser);
struct ParseStmts *parse_while(struct ParseStmts *parser) ;
struct Parser *new_parser(struct Lexer *lexer);
struct Parser *parse_expr(struct Lexer *lexer);
void parse_expr_precedence(struct Parser *parser, struct Expr *left, int min_precedence);
void parse_literal(struct Parser *parser);
bool parse_simple_tok(struct ParseStmts *parser, enum SimpleToken st, const char *err);
struct FunctionCall *parse_function_call(void);
